### ISSUE TITLE
juniper_actix with subscriptions feature doesn't compile

### ISSUE THREAD

**Issue by AadamZ5** [graphql-rust/juniper#1063]
### Disclaimer
I am a rust newbie! I may be grossly misusing something here

**Describe the bug**
`juniper_actix` with `subscriptions` feature does not compile in my project. To be clear, the dependency itself does not compile, compilation does not reach my program.

Main error is:
```
error[E0277]: the trait bound `SubscriptionActor<Query, Mutation, Subscription, CtxT, S, I>: actix::actor::Actor` is not satisfied
```
in multiple spots

<details>
  <summary>List of errors from compiler</summary>
<pre><code>
error[E0277]: the trait bound `SubscriptionActor<Query, Mutation, Subscription, CtxT, S, I>: actix::actor::Actor` is not satisfied
   --> /home/azocolo/.cargo/registry/src/github.com-1ecc6299db9ec823/juniper_actix-0.4.0/src/lib.rs:320:80
    |
320 |         fn handle(&mut self, msg: Result<ws::Message, ws::ProtocolError>, ctx: &mut Self::Context) {
    |                                                                                ^^^^^^^^^^^^^^^^^^ the trait `actix::actor::Actor` is not implemented for `SubscriptionActor<Query, Mutation, Subscription, CtxT, S, I>`
    |
note: required by a bound in `WebsocketContext`
   --> /home/azocolo/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-actors-4.1.0/src/ws.rs:370:8
    |
370 |     A: Actor<Context = WebsocketContext<A>>,
    |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `WebsocketContext`

error[E0277]: the trait bound `SubscriptionActor<Query, Mutation, Subscription, CtxT, S, I>: actix::actor::Actor` is not satisfied
   --> /home/azocolo/.cargo/registry/src/github.com-1ecc6299db9ec823/juniper_actix-0.4.0/src/lib.rs:358:24
    |
358 |         type Context = ws::WebsocketContext<Self>;
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `actix::actor::Actor` is not implemented for `SubscriptionActor<Query, Mutation, Subscription, CtxT, S, I>`
    |
note: required by a bound in `WebsocketContext`
   --> /home/azocolo/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-actors-4.1.0/src/ws.rs:370:8
    |
370 |     A: Actor<Context = WebsocketContext<A>>,
    |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `WebsocketContext`

error[E0277]: the trait bound `SubscriptionActor<Query, Mutation, Subscription, CtxT, S, I>: actix::actor::Actor` is not satisfied
   --> /home/azocolo/.cargo/registry/src/github.com-1ecc6299db9ec823/juniper_actix-0.4.0/src/lib.rs:360:36
    |
360 |         fn started(&mut self, ctx: &mut Self::Context) {
    |                                    ^^^^^^^^^^^^^^^^^^ the trait `actix::actor::Actor` is not implemented for `SubscriptionActor<Query, Mutation, Subscript
    |
note: required by a bound in `WebsocketContext`
   --> /home/azocolo/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-actors-4.1.0/src/ws.rs:370:8
    |
370 |     A: Actor<Context = WebsocketContext<A>>,
    |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `WebsocketContext`

error[E0277]: the trait bound `SubscriptionActor<Query, Mutation, Subscription, CtxT, S, I>: actix::actor::Actor` is not satisfied
   --> /home/azocolo/.cargo/registry/src/github.com-1ecc6299db9ec823/juniper_actix-0.4.0/src/lib.rs:377:34
    |
377 |         fn stopped(&mut self, _: &mut Self::Context) {
    |                                  ^^^^^^^^^^^^^^^^^^ the trait `actix::actor::Actor` is not implemented for `SubscriptionActor<Query, Mutation, Subscription, CtxT, S, I>`
    |
note: required by a bound in `WebsocketContext`
    |
370 |     A: Actor<Context = WebsocketContext<A>>,
    |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `WebsocketContext`

error[E0277]: the trait bound `SubscriptionActor<Query, Mutation, Subscription, CtxT, S, I>: actix::actor::Actor` is not satisfied
   --> /home/azocolo/.cargo/registry/src/github.com-1ecc6299db9ec823/juniper_actix-0.4.0/src/lib.rs:401:18
    |
401 |             ctx: &mut Self::Context,
    |                  ^^^^^^^^^^^^^^^^^^ the trait `actix::actor::Actor` is not implemented for `SubscriptionActor<Query, Mutation, Subscription, CtxT, S, I>`
    |
note: required by a bound in `WebsocketContext`
   --> /home/azocolo/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-web-actors-4.1.0/src/ws.rs:370:8
    |
370 |     A: Actor<Context = WebsocketContext<A>>,
    |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `WebsocketContext`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `juniper_actix` due to 5 previous errors
</code></pre>
</details>

**To Reproduce**
- Make a new binary project `cargo new juniper-actix-subscriptions-problem`
- Add dependencies (Using `cargo add` from `cargo-edit` tool shown below, or refer to toml at bottom)
  - `cargo add actix_web`
  - `cargo add juniper`
  - `cargo add juniper_actix --features=subscriptions`
- Simply run `cargo check` to force dependencies to compile. 
- Observe error

**Expected behavior**
Dependencies compile with no issues

**Additional context**
Cargo.toml:
```toml
[package]
name = "problem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.1"
juniper = "0.15.9"
juniper_actix = { version = "0.4.0", features = ["subscriptions"] }
```

**Comment by tyranron** [comment]
@AadamZ5 yup `juniper_actix` 0.4 doesn't work well with `actix-web` `^4.0`, cause it still depends on beta versions.

This is fixed on `master`. Hasn't been released yet, though. I'll recommend to try latest `master`. There are some significant changes and better ergonomics.

**Comment by Abhay478** [comment]
Encountered same bug. Still an issue. Any help sorting out the versions would be greatly appreciated. Currently, I'm using:

```
actix-web = "4.3.0"                         
juniper_actix = {version = "0.4.0", features = ["subscriptions"]}       
juniper_subscriptions = "0.16.0"  
juniper_graphql_ws = "0.3.0
```
