### ISSUE TITLE
`FieldResult` should "bubble up" in case of an error when the field is declared as Non-Null

### ISSUE THREAD

**Issue by rushmorem** [graphql-rust/juniper#84]
The spec says:

> If the field which experienced an error was declared as Non-Null, the null result will bubble up to the next nullable field. In that case, the path for the error should include the full path to the result field where the error occurred, even if that field is not present in the response.

This is not the current behaviour. Currently the `null` does not "bubble up". As a result, a field that was declared `Non-Null` will return a `null` when that field produces an error.

**Comment by jacobh** [comment]
Any progress on this one? It bit us today. Happy to help where possible

**Comment by rushmorem** [comment]
> Any progress on this one?

I don't know if anyone is currently working on this.

/cc @mhallin

**Comment by mhallin** [comment]
This issue has been resolved on the master branch and will be part of the next release.

**Comment by jacobh** [comment]
Wonderful, thanks @mhallin !

**Comment by jacobh** [comment]
I think there's still an issue here for array fields.

I've got a schema that looks like

```graphql
schema {
  query: Query
  mutation: Mutations
}

# DateTime
scalar DateTimeUtc

type Query {
  queueEntry(id: Uuid!): QueueEntry
  session(id: Uuid!): Session
}

type QueueEntry {
  id: Uuid!
  session: Session!
}

type Session {
  id: Uuid!
  queueEntries: [QueueEntry!]!
}

# Uuid
scalar Uuid
```

I've modified the `QueueEntry.session` field to intentionally break it, and when looking up a specific `QueueEntry` this change works as expected

```graphql
{
  queueEntry(id: "f01f415f-42fc-4e49-9600-56227e2edd96") {
    id
    session {
      id
    }
  }
}
```
```json
{
  "data": {
    "queueEntry": null
  },
  "errors": [
    {
      "message": "Fake Error",
      "locations": [
        {
          "line": 4,
          "column": 5
        }
      ],
      "path": [
        "queueEntry",
        "session"
      ]
    }
  ]
}
```

However, when I query a `Session`, and get the list of related `QueueEntry`s, I get an array of `null`s

```graphql
{
  session(id: "9cc55702-6c3e-491e-b259-e8c6982c6073") {
    id
    queueEntries {
      id
      session {
        id
      }
    }
  }
}
```
```json
{
  "data": {
    "session": {
      "id": "9cc55702-6c3e-491e-b259-e8c6982c6073",
      "queueEntries": [
        null,
        null,
        null
      ]
    }
  },
  "errors": [
    {
      "message": "Fake Error",
      "locations": [
        {
          "line": 9,
          "column": 7
        }
      ],
      "path": [
        "session",
        "queueEntries",
        "session"
      ]
    },
    {
      "message": "Fake Error",
      "locations": [
        {
          "line": 9,
          "column": 7
        }
      ],
      "path": [
        "session",
        "queueEntries",
        "session"
      ]
    },
    {
      "message": "Fake Error",
      "locations": [
        {
          "line": 9,
          "column": 7
        }
      ],
      "path": [
        "session",
        "queueEntries",
        "session"
      ]
    }
  ]
}
```

**Comment by mhallin** [comment]
Thanks for reporting and creating a test case for this! Cases where we deviate from the spec are serious issues, so please keep reporting these if you find more :)

The non-nullable list issue _should_ be resolved now, the test case you created passes on master.

**Comment by jacobh** [comment]
That patch has done the trick! thanks again
